
const PRODUCTS = [
  {
    id: "P001",
    name: "Knife Blade Set",
    price: 1450,
    oldPrice: 1699,
    brand: "New Hira",
    model: "985 Standard",
    machineType: "Combine Harvester",
    category: "Cutting",
    partNo: "NH-985-KB-11",
    compatibility: ["New Hira 985 Standard", "Cutter Bar 5ft"],
    stock: 24,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80",
    description: "Hardened steel knife blade set for cleaner crop cutting, smoother operation, and longer field life."
  },
  {
    id: "P002",
    name: "Ledger Plate",
    price: 680,
    oldPrice: 799,
    brand: "New Hira",
    model: "985 Deluxe",
    machineType: "Cutter Bar",
    category: "Cutting",
    partNo: "NH-985-LP-22",
    compatibility: ["New Hira 985 Deluxe", "Cutter Bar 6ft"],
    stock: 41,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=1200&q=80",
    description: "Precision ledger plate built for better cutting efficiency and reliable support in paddy and wheat conditions."
  },
  {
    id: "P003",
    name: "Reel Finger Assembly",
    price: 2150,
    oldPrice: 2499,
    brand: "New Hira",
    model: "985 Standard",
    machineType: "Combine Harvester",
    category: "Feeding",
    partNo: "NH-RF-307",
    compatibility: ["New Hira 985 Standard", "New Hira 985 Deluxe"],
    stock: 18,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80",
    description: "Strong reel finger assembly for smooth crop feeding and reduced grain loss during harvesting."
  },
  {
    id: "P004",
    name: "Thresher Concave",
    price: 5850,
    oldPrice: 6499,
    brand: "Sonalika",
    model: "Multicrop",
    machineType: "Combine Harvester",
    category: "Threshing",
    partNo: "SN-CC-104",
    compatibility: ["Sonalika Multicrop", "Universal Combine 4ft"],
    stock: 9,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    description: "Heavy-duty concave for efficient grain separation with strong wear resistance in extended operations."
  },
  {
    id: "P005",
    name: "Straw Walker Bearing",
    price: 920,
    oldPrice: 1099,
    brand: "Preet",
    model: "987",
    machineType: "Straw Reaper",
    category: "Bearing",
    partNo: "PR-SWB-88",
    compatibility: ["Preet 987", "Straw Reaper Standard"],
    stock: 35,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=1200&q=80",
    description: "High-load bearing engineered for straw handling systems and rough seasonal farm usage."
  },
  {
    id: "P006",
    name: "Auger Flighting Section",
    price: 3350,
    oldPrice: 3799,
    brand: "New Holland",
    model: "TC Series",
    machineType: "Combine Harvester",
    category: "Grain Handling",
    partNo: "NHL-AF-52",
    compatibility: ["New Holland TC Series", "Universal Grain Tank Auger"],
    stock: 13,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80",
    description: "Balanced auger flighting section for smooth grain movement and reduced loading vibration."
  },
  {
    id: "P007",
    name: "Elevator Chain Kit",
    price: 2650,
    oldPrice: 2999,
    brand: "Dasmesh",
    model: "9100",
    machineType: "Combine Harvester",
    category: "Transmission",
    partNo: "DM-ECK-90",
    compatibility: ["Dasmesh 9100", "Universal Elevator Housing"],
    stock: 27,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=1200&q=80",
    description: "Ready-fit elevator chain kit designed for durable operation under dusty and heavy-yield conditions."
  },
  {
    id: "P008",
    name: "Cutter Bar Guard",
    price: 540,
    oldPrice: 620,
    brand: "New Hira",
    model: "985 Deluxe",
    machineType: "Cutter Bar",
    category: "Cutting",
    partNo: "NH-CBG-13",
    compatibility: ["New Hira 985 Deluxe", "Cutter Bar 5ft", "Cutter Bar 6ft"],
    stock: 54,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?auto=format&fit=crop&w=1200&q=80",
    description: "Reinforced cutter bar guard for blade protection, better alignment, and stable field performance."
  },
  {
    id: "P009",
    name: "Pulley Belt Premium",
    price: 1180,
    oldPrice: 1390,
    brand: "Mahindra",
    model: "Arjun Harvester",
    machineType: "Straw Reaper",
    category: "Transmission",
    partNo: "MH-PB-77",
    compatibility: ["Mahindra Arjun Harvester", "Straw Reaper Premium"],
    stock: 31,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80",
    description: "Heat-resistant pulley belt with stable grip and dependable performance during peak season use."
  },
  {
    id: "P010",
    name: "Sieve Top Panel",
    price: 2890,
    oldPrice: 3299,
    brand: "Sonalika",
    model: "Multicrop",
    machineType: "Combine Harvester",
    category: "Cleaning",
    partNo: "SN-STP-31",
    compatibility: ["Sonalika Multicrop", "Cleaning Shoe Standard"],
    stock: 11,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80",
    description: "Efficient sieve top panel built to improve grain cleaning and reduce unwanted residue carryover."
  },
  {
    id: "P011",
    name: "Feed Conveyor Slat",
    price: 1540,
    oldPrice: 1790,
    brand: "Preet",
    model: "987",
    machineType: "Combine Harvester",
    category: "Feeding",
    partNo: "PR-FCS-17",
    compatibility: ["Preet 987", "Universal Feed Conveyor"],
    stock: 22,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    description: "Durable feed conveyor slat for controlled crop movement and reduced intake blockage."
  },
  {
    id: "P012",
    name: "Chopper Blade Set",
    price: 3780,
    oldPrice: 4199,
    brand: "New Hira",
    model: "985 Standard",
    machineType: "Straw Reaper",
    category: "Residue Management",
    partNo: "NH-CBS-73",
    compatibility: ["New Hira 985 Standard", "New Hira 985 Deluxe", "Straw Reaper Standard"],
    stock: 16,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1499529112087-3cb3b73cec95?auto=format&fit=crop&w=1200&q=80",
    description: "Premium chopper blade set for consistent straw processing and long service life."
  }
];
